// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DongTaBhxh.Domain.Models.EmployeeDb;

public partial class Department
{
    public int DepartmentId { get; set; }

    public string ShortName { get; set; } = null!;

    public string Name { get; set; } = null!;

    public int? Score { get; set; }

    public bool IsActivity { get; set; }

    public string? Email { get; set; }

    public string? Phone { get; set; }

    public int? SortOrder { get; set; }

    public int LevelId { get; set; }
    public virtual Level? Level { get; set; } 
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<QuarterDepartmentRank> QuarterDepartmentRanks { get; set; } = new List<QuarterDepartmentRank>();
}

/// <summary>
/// Cấp hành chính
/// </summary>
public partial class Level {
    public int LevelId { get; set; }
    public string Name { get; set; } = null!;
    public string? ShortName { get; set; }
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}