// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DongTaBhxh.Domain.Models.EmployeeDb;

public partial class Position
{
    public int PositionId { get; set; }

    public string Name { get; set; } = null!;

    public string? ShortName { get; set; }

    public string? Note { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}