// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DongTaBhxh.Domain.Models.EmployeeDb;

public partial class SalaryCoefficient
{
    public int SalaryCoefficientId { get; set; }

    public byte Rank { get; set; }

    public double Coeficient { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}